version: "3.8"
services:
  app:
    container_name: astral_app
    build: "."
    restart: unless-stopped
    volumes:
      - "./uploads:/app/uploads"
    ports:
      - "8080:8080"
    depends_on:
      - "postgres_db"

  postgres_db:
    image: "postgres"
    container_name: "astral_postgres"
    restart: "unless-stopped"
    env_file:
      - ".env"
    ports:
      - "5440:5432"